---STRING FONKSIYONLAR


DECLARE @KELIME AS VARCHAR(100)

SET @KELIME= 'MERHABA DUNYA'

SELECT SUBSTRING(@KELIME,9,5)



---LOWER, UPPER

DECLARE @KELIME AS VARCHAR(100)

SET @KELIME= 'MERHABA DUNYA'

SELECT LOWER(@KELIME), UPPER(@KELIME) 



------STRING BIRLESTIRME

DECLARE @AD AS VARCHAR(100)='OMER'
DECLARE @SOYAD AS VARCHAR(100)='COLAKOGLU'
SELECT @AD +'  '+@SOYAD


-----RIGHT, LEFT

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME= 'MERHABA DUNYA'
SELECT LEFT(@KELIME, 10), RIGHT(@KELIME,5)


-----LTRIM, RTRIM, TRIM/ BOSLUK TEMIZLEYEN KOMUTLAR

DECLARE @KELIME AS VARCHAR(100)='  MERHABA DUNYA     '
SELECT LTRIM(@KELIME),RTRIM(@KELIME),TRIM(@KELIME),LTRIM(RTRIM(@KELIME))



----REPLACE

DECLARE @KELIME AS VARCHAR(100)='MERHABA DUNYA'
SELECT REPLACE(@KELIME, 'MERHABA', 'HELLO')


---LEN
DECLARE @KELIME AS VARCHAR(100)='MERHABA DUNYA'
SELECT LEN(@KELIME)


----STRING_SPLIT
DECLARE @KELIME AS VARCHAR(100)='MERHABA DUNYA'
SELECT
* FROM string_split(@KELIME,' ')


DECLARE @KELIME AS VARCHAR(100)='BTK AKADEMISI BUNYESINDE DUZENLENEN SQL SERVER EGITIMI'
SELECT 
*FROM string_split(@KELIME,' ')