---STRING FUNCTIONS

DECLARE @WORD AS VARCHAR(100)
SET @WORD = 'HELLO WORLD'
SELECT SUBSTRING(@WORD, 9, 5)

---LOWER, UPPER

DECLARE @WORD AS VARCHAR(100)
SET @WORD = 'HELLO WORLD'
SELECT LOWER(@WORD), UPPER(@WORD)

------STRING CONCATENATION

DECLARE @FIRSTNAME AS VARCHAR(100) = 'OMER'
DECLARE @LASTNAME AS VARCHAR(100) = 'COLAKOGLU'
SELECT @FIRSTNAME + ' ' + @LASTNAME

-----RIGHT, LEFT

DECLARE @WORD AS VARCHAR(100)
SET @WORD = 'HELLO WORLD'
SELECT LEFT(@WORD, 10), RIGHT(@WORD, 5)

-----LTRIM, RTRIM, TRIM/ REMOVING WHITESPACE

DECLARE @WORD AS VARCHAR(100) = '  HELLO WORLD     '
SELECT LTRIM(@WORD), RTRIM(@WORD), TRIM(@WORD), LTRIM(RTRIM(@WORD))

----REPLACE

DECLARE @WORD AS VARCHAR(100) = 'HELLO WORLD'
SELECT REPLACE(@WORD, 'HELLO', 'HI')

---LEN
DECLARE @WORD AS VARCHAR(100) = 'HELLO WORLD'
SELECT LEN(@WORD)

----STRING_SPLIT
DECLARE @WORD AS VARCHAR(100) = 'SQL Server is a powerful database management system'
SELECT * FROM STRING_SPLIT(@WORD, ' ')

DECLARE @WORD AS VARCHAR(100) = 'Learning SQL and improving database skills is essential'
SELECT * FROM STRING_SPLIT(@WORD, ' ')
